#### 开发环境配置
##### Basic
server:
  port: 18624
  ssl:
    #    证书路径
    key-store: 0_sgcc.link.jks
    key-store-type: JKS
    #      key-alias: tomcat
    #    配置密码，就是在生成证书的时候输入的密码
    key-store-password: bt.cn

##### Spring
spring:
  application:
    name: sgcc
  ### Redis
  redis:
    #    database: 1
    #     192.168.0.108  47.100.91.115
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  ### mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.22.176:3306/sgcc_cd
    username: root
    password: Root@123
  activemq:
    broker-url: tcp://47.100.91.115:61616
    in-memory: false
    pool:
      enabled: false #如果此处设置为true，需要加如下的依赖包，否则会自动配置失败，报JmsMessagingTemplate注入失败
###fdfs
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  reqHost: 119.23.22.176   #nginx访问地址
  reqPort: 18625
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  web-server-url: https://www.sgcc.link:18625/
  tracker-list: 119.23.22.176:22122

    ### Data
    ### postgresql
    #  datasource:
    #    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://192.168.1.71:5432/fangsheng0705
    #    username: fp
    #    password: fp@123
    ### Data
    #  data:
    # Cassandra
    #    cassandra:
    #      keyspace-name: newfront
    #      contact-points: 192.168.1.101
    #      port: 9042
    #      repositories:
    #        type: auto
    #      schema-action: create_if_not_exists
  # Elasticsearch
#    elasticsearch:
#      cluster-nodes: 192.168.1.97:9300
#      # 不加 cluster-name 属性会报错:
#      #   NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{jyzih8cJQj6axOEAERo7ew}{192.168.1.97}{192.168.1.97:9300}]]
#      # 其他解决方案暂不清楚
#      cluster-name: my-application
#      repositories:
#        enabled: true


##### Log
logging:
  level:
    root: info

precompile: true

spring.datasource.hikari.minimum-idle: 3
spring.datasource.hikari.maximum-pool-size: 10
spring.datasource.hikari.max-lifetime: 30000 # 不能小于30秒，否则默认回到1800秒
spring.datasource.hikari.connection-test-query: SELECT 1